# Generated by Django 4.2.3 on 2023-08-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wonder_fields", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="chat_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="tg_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
